### ISSUE TITLE
[Bug] - Navbar toggle is not visible in Light Mode 

### ISSUE THREAD

**Issue by khalidatcodiga** [codiga/doc.codiga.io#2]
The Navbar toggle in light mode is not visible. It should be visible in both light and dark mode:

This bug is visible on mobile view

![Screenshot](https://user-images.githubusercontent.com/99663873/157302390-a7ac83e3-f7f4-49cf-9192-22a4da7e6df4.png)

**Comment by HritikR** [comment]
Hi @khalidatcodiga, I would like to work on this issue.

**Comment by khalidatcodiga** [comment]
Hey @HritikR , Go ahead and put up a PR
